### ISSUE TITLE
Date à prendre en compte pour date de parution

### ISSUE THREAD

**Issue by zakxxi** [abrege/lerouergue#110]
Nous partons sur le champ "firstpublicationdate" de manière à ne pas se retrouver avec les réimpressions simples en nouveautés. Du coup, nous n'aurons que les mois et années pour les nouveautés mais c'est déjà pas mal !

Par contre c'est un peu tricky, c'est un champ texte avec le format 2/2006, 11/2005…

fonction prepareRow()
$date = $row->firstpublicationdate;
$date_parts = explode('/', $date);
$row->firstpublicationdate =
$date_parts[1] . '-' . $date_parts[0] . '-01';

**Comment by jabberwooki** [comment]
Corrigé.
Mais comme les mois ne sont pas tous avec deux chiffres (ex. déc=12, mai=5), le code exact est : 

$date_parts = explode('/', $row->firstpublicationdate);
$date_parts[0] = ($date_parts[0] < 10) ?  '0' . $date_parts[0] : $date_parts[0]
$row->firstpublicationdate = $date_parts[1] . '-' . $date_parts[0] . '-01';
