### ISSUE TITLE
Règle pour le bloc vue "livres du même auteur"

### ISSUE THREAD

**Issue by zakxxi** [abrege/lerouergue#111]
Voici ce que je pense OK pour le bloc vue "livres du même auteur" à reconstruire car plusieurs bugs (affichage des traducteurs, livres manquants sur certaines fiches > Colette Gouvion)

Il faut charger dans cette vue :
les livres du ou des mêmes
• auteur
• illustrateur
sans tenir compte du champ "auteur principal"
aucun autre contributeur ne dois être affiché dans cette vue.

Pouvez-vous me confirmer cette règle côté Rouergue ? :+1:

**Comment by Rouergue** [comment]
On ne prend en compte que l'auteur principal pour les livres "du même auteur"

**Comment by zakxxi** [comment]
DONC AFFICHER :

• AUTEUR + AUTEUR PRINCIPAL
• DIRECTEUR D'OUVRAGE + AUTEUR PRINCIPAL

On ne prends pas en compte tous les autres contributeurs.

**Comment by zakxxi** [comment]
Bravo !
