### ISSUE TITLE
Champ contributeur vide dans l'admin

### ISSUE THREAD

**Issue by zakxxi** [abrege/lerouergue#112]
![image](https://cloud.githubusercontent.com/assets/1446617/9938452/b594efee-5d65-11e5-9edd-d72270af570e.png)

relié à l'erreur "Could not find host entity of the field collection to import."
drush mi articleContributors --update

**Comment by zakxxi** [comment]
Alors après quelques test… Au premier import tout est bon malgré l'erreur :
`Could not find host entity of the field collection to import.               [error]` dans la console

Lors d'une màj via `drush mi article --update && drush mi articleContributors --update` autant de contributeurs "VIDES" que de "VRAIS" contributeurs sont ajoutés. Si on a 3 contributeurs à la base, à la première màj on passe à 6.

On a aussi le message d'erreur `Notice : Trying to get property of non-object dans field_collection_field_get_entity() (ligne 1681 dans /Users/zak/Sites/lerouergue/profiles/rouergue/modules/contrib/field_collection/field_collection.module).`

Je pense qu'il faut donc chercher du côté de Field Collection, j'ai trouvé ces ressources pouvant peut être aider :+1: 
https://www.drupal.org/node/1900640#comment-10118550
https://www.drupal.org/node/1175082

**Comment by jabberwooki** [comment]
Les mises à jour conservent maintenant les bonnes données contributeurs.
Correction effectuée dans la fonction prepare() de la classe ArticleMigration dans la feature Catalog.
