### ISSUE TITLE
Mention du pays dans AGENDA à faire manuellement ? 

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#120]
Ou bien il faut rajouter des pays à la liste (il n'y a que la France et la Belgique, il faudrait notamment ajouter la Suisse). Puis-je le faire moi-même directement ?

**Comment by zakxxi** [comment]
Il faut lister tous les pays.

**Comment by jabberwooki** [comment]
Le paramétrage se fait ici : 
http://rouergue/admin/structure/types/manage/event/fields/field_adresse

Si des noms de pays sont sélectionnés, seuls ces pays apparaissent dans la liste du champ Adresse des événéments. Si aucun n'est coché, ils apparaissent tous.
Pour l'instant, France et Belgique sont cochés.

**Comment by zakxxi** [comment]
J'ai rajouté la Suisse et le Canada, si il y'a besoin de nouveaux pays à terme François pourra les ajouter depuis l'administration Drupal via le paramétrage indiqué par Christophe ci-dessus.
