### ISSUE TITLE
Fabrique : masquer le titre du bloc "livre lié" quand il est vide.

### ISSUE THREAD

**Issue by zakxxi** [abrege/lerouergue#124]
![image](https://cloud.githubusercontent.com/assets/1446617/10042159/f280b694-61e9-11e5-8e53-2dbe59dbce89.png)

**Comment by jabberwooki** [comment]
Corrigé.

_Info technique : test effectué sur la présence, dans le $data['content']['#markup'] du block "livre lié", de la chaine de caractère **typeof="sioc:Item foaf:Document"**
Si la chaine n'est pas présente, c'est que le bloc ne contient rien. Le titre du bloc est retiré._

**Comment by zakxxi** [comment]
Ça fonctionne dans mon environnement dev mais pas sur la prod. Une idée ?
http://prod.lerouergue.com/fabrique/un-nouveau-roman-lautomne-dans-la-collection-epik
![image](https://cloud.githubusercontent.com/assets/1446617/10309647/0ac008b4-6c3e-11e5-86a1-c037b3bd62db.png)
