### ISSUE TITLE
Impossibilité de faire apparaître les nouveautés parues depuis août. 

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#127]
Est-ce dû au pb de dates dont nous avions parlé ?
(du coup, je ne peux pas créer le bandeau sur la page d'accueil avec les nouveautés)

**Comment by zakxxi** [comment]
C'est normal car nous respectons la règle suivante :
![image](https://cloud.githubusercontent.com/assets/1446617/10191121/a2b3c876-6771-11e5-870e-d3b89f7d2d95.png)

Et pour certains livres le prix n'est pas renseigné dans la table mistral "realprice"
![image](https://cloud.githubusercontent.com/assets/1446617/10191146/cdd88712-6771-11e5-87c2-837e1e8a5f13.png)

Il faut donc renseigner le champ prix côté mistral.

**Comment by zakxxi** [comment]
![image](https://cloud.githubusercontent.com/assets/1446617/10193644/a1f84566-6784-11e5-9aed-f88b13311a17.png)
![image](https://cloud.githubusercontent.com/assets/1446617/10193675/e267ead4-6784-11e5-8ac8-b73307abb347.png)

**Comment by Fchallier** [comment]
Je viens  de regarder directement sur la base du serveur mistral. 
J'ai testé la requéte qui génère le dump pour le Rouergue et le champ s'affiche bien. 
![rqt_mistral](https://cloud.githubusercontent.com/assets/9974750/10195217/c78bcd7c-678c-11e5-97a8-bf4a3e69c1ba.png)

Mais c'est de lors de l'import sur le serveur qu'il y a un problème. Je continue de chercher la raison !

**Comment by Fchallier** [comment]
Probléme corrigé au niveau de l'import. 

J'ai envoyé un nouveau dump sur le serveur de prod. Vous pouvez vérifier de votre côté  ?

**Comment by zakxxi** [comment]
Ok je teste !
