### ISSUE TITLE
Champ code postal qui disparaît dans le formulaire agenda

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#131]
Ce n'est pas systématique mais cela arrive de temps en temps...

![capture d ecran 2015-09-30 a 09 23 24](https://cloud.githubusercontent.com/assets/10072454/10186967/4080c8aa-6755-11e5-9593-1f89941fe349.png)

**Comment by zakxxi** [comment]
Probablement du à la connexion internet ou à la machine client, non reproductible de notre côté.
