### ISSUE TITLE
Cartouche d'erreur quand on passe du champ "visuel" à la "description" (dans l'AGENDA)

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#133]
![capture d ecran 2015-09-29 a 16 04 31](https://cloud.githubusercontent.com/assets/10072454/10187089/18296f14-6756-11e5-9fba-084bbc4a8f4e.png)

**Comment by zakxxi** [comment]
Probablement du à un envoi d'image trop volumineux, essayer de rester inférieur à 1 Mo.
