### ISSUE TITLE
Mention "épuisé" qui n'apparaît pas sur drupal 

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#134]
(alors que la mention est bien dans mistral)
exemple 

![capture d ecran 2015-09-30 a 16 40 44](https://cloud.githubusercontent.com/assets/10072454/10196258/48d7c426-6792-11e5-8e6a-21348efde195.png)

![capture d ecran 2015-09-30 a 16 42 15](https://cloud.githubusercontent.com/assets/10072454/10196249/39d09052-6792-11e5-9bcc-e452be61e547.png)

**Comment by jabberwooki** [comment]
Corrigé.
(Info technique : le problème venait du fait que le champ Display Suite nommé Publication status était décalé sur la droite dans l'écran de paramétrage du mode Contenu complet au lieu d'être aligné complètement à gauche. Le réaligner a suffit à le faire apparaître sur la fiche livre.
