### ISSUE TITLE
Titres qui n'apparaissent pas dans l'univers adéquat

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#141]
Pourquoi L'EXACTITUDE DES SONGES, SADE UP, TRIBULATIONS PLASTIQUES n'apparaissent pas dans l'univers "Objets littéraires" alors que, dans mistral, ils sont bien dans les collections "Rouergue Beaux-Livres" ou "Rouergue Littérature" > sous coll. "objet littéraire" ?

![capture d ecran 2015-10-06 a 10 47 38](https://cloud.githubusercontent.com/assets/10072454/10303998/b6f540da-6c17-11e5-83b9-d20982f6f955.png)

![capture d ecran 2015-10-06 a 10 43 24](https://cloud.githubusercontent.com/assets/10072454/10304002/ba4538bc-6c17-11e5-8bf1-2ba3a43000ba.png)

**Comment by zakxxi** [comment]
Petit bug dans le mapping c'est corrigé.
