### ISSUE TITLE
Pb de connexion en tant que webmaster

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#142]
Arrrgh... Je ne peux plus me connecter sur le site comme webmaster, l'accès m'est refusé.
Et il se passe de drôles de choses au niveau de l'affichage des couvertures (en polars notamment). 
Est-ce parce que tu es en train de travailler dessus, Adrien ? Vaut-il mieux que j'attende que tu aies fini ?

![capture d ecran 2015-10-06 a 11 34 24](https://cloud.githubusercontent.com/assets/10072454/10305080/63b38a42-6c1e-11e5-947a-0e6ed3554a4c.png)

**Comment by zakxxi** [comment]
Oui je travaille dessus je suis en train de mettre à jour avec les modifs de mapping et de droits,
par contre j'attends une manip de François que je ne peux pas faire sur le serveur pour le problème des couvs.

**Comment by zakxxi** [comment]
Il faudra sans doutes te déconnecter puis te reconnecter.

**Comment by Rouergue** [comment]
j'ai essayé, mais ça ne fonctionne toujours pas. Faut-il que je redémarre mon ordi ?
