### ISSUE TITLE
Quel format pour les bandeaux actu ?

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#144]
Sur l'interface de l'admin, c'est indiqué 850 x 425 px 

![capture d ecran 2015-10-06 a 17 02 23](https://cloud.githubusercontent.com/assets/10072454/10312583/17134eba-6c4c-11e5-8e01-42137fd9bd58.png)

Mais, quand je respecte ces dimensions, cela me coupe l'image

![capture d ecran 2015-10-06 a 17 03 38](https://cloud.githubusercontent.com/assets/10072454/10312613/36599c84-6c4c-11e5-9262-9acb589386cc.png)

Et si je respecte le format "visible" à l'écran, soit 1142 x 302 px, l'image est refusée

![capture d ecran 2015-10-06 a 16 53 26](https://cloud.githubusercontent.com/assets/10072454/10312629/4bd1f6ec-6c4c-11e5-843d-c0e7f0513617.png)

Quid ?

**Comment by zakxxi** [comment]
1140x300

**Comment by zakxxi** [comment]
Oubli de config, c'est réparé.
