### ISSUE TITLE
photo auteur manquante

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#147]
exemple pour M. Leblond, alors que sa photo (12709) fait bien partie du dossier des photos envoyées.

![capture d ecran 2015-10-07 a 10 00 04](https://cloud.githubusercontent.com/assets/10072454/10332009/549b9178-6cda-11e5-9b03-44a7704706c7.png)

**Comment by Fchallier** [comment]
Mathilde,  les photos que tu m'as envoyé hier je n'ai pas eu le temps de les traiter. 

Mais le systeme de mise à jour d'Adrien et Christophe fonctionne.

**Comment by Rouergue** [comment]
Ok, tout va bien alors. Désolée pour la pression ! 
C'est juste que j'avais peur que ce soit un bug.
