### ISSUE TITLE
impossible de mettre des pages intérieures pour le feuilletage

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#148]
J'ai essayé avec un pdf de 45 mo (au niveau d'une page livreà et ça me met :

![capture d ecran 2015-10-07 a 10 06 56](https://cloud.githubusercontent.com/assets/10072454/10332135/8d7baaae-6cdb-11e5-9fa7-820c69b67e1f.png)

**Comment by zakxxi** [comment]
45 Mo beaucoup trop lourd ! Il faudrait se limiter à 5 Mo pour les PDF. Pour l'instant nous n'avons pas mis de limite sur le champ mais il faudrait peut-être le faire afin d'éviter ces erreurs.

**Comment by Rouergue** [comment]
comme c'était marqué 50 Mo max, je me suis dit que j'avais un peu de marge !!!
Bon ok, c'était un peu exagéré !
