### ISSUE TITLE
où sont les "à paraître" ? 

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#149]
Sur le site, il n'y a pas, par exemple LA RÉVOLTE D'EVA (14 octobre) ou EXPLO-RATEUR (21 octobre) alors qu'ils sont bien sur mistral. 

![capture d ecran 2015-10-07 a 10 24 38](https://cloud.githubusercontent.com/assets/10072454/10332469/bb13ec18-6cdd-11e5-8aac-72383106f15a.png)

**Comment by zakxxi** [comment]
À paraître le 4/11

DANS LE SILENCE ENTERRÉ
L'ACCÉLÉRATEUR D'AMOUR
LES COPIES

**Comment by zakxxi** [comment]
Normal que ces livres ne soient pas importés, et pour 2 raisons différentes.

Pour : LA RÉVOLTE D'EVA & EXPLO-RATEUR le Statut est égal à NULL (cf ta capture d'écran)
![capture d ecran 2015-10-07 15 28 01](https://cloud.githubusercontent.com/assets/1446617/10338759/0ad7ef22-6d08-11e5-871f-4f8eb088f8b7.png)

Pour les titres à paraître en Novembre on a pas de prix ou celui-ci n'est pas validé :
![capture d ecran 2015-10-07 14 02 42](https://cloud.githubusercontent.com/assets/1446617/10338781/2246019e-6d08-11e5-9148-07cbca44d2ed.png)

Ce sont donc des problèmes venant de MISTRAL. La mécanique d'import est conforme à la demande.

**Comment by Rouergue** [comment]
![capture d ecran 2015-10-14 a 11 30 55](https://cloud.githubusercontent.com/assets/10072454/10479863/0e0f8538-7267-11e5-91a0-c09aceae9065.png)

**Comment by Fchallier** [comment]
Je viens d'envoyer un nouveau dump sur le seveur. Dans /www/lerouergue_data/mistral_dumps

Donc maintenant l'ensemble des "Isvalidated" de la table "priceandtirage" sont soit à 1 soit à 0. Plus aucun champ null ou =''.

Par contre pour les "Statusid" de la table article, je viens de regarder avec le dernier dump et les derniers articles à "null" ou  ='' correspondent uniquement  à des PLV qui ne sont pas importés.

**Comment by Fchallier** [comment]
Pardon, une petite erreur au niveau du dernier dump, notament pour le "Statusi
Je corrige ça tout de suite

**Comment by Fchallier** [comment]
Dump à jour dans /www/lerouergue_data/mistral_dumps.

**Comment by zakxxi** [comment]
OK je relance une migration dans la soirée, on fait un point demain matin.

**Comment by zakxxi** [comment]
Après nouvelle migration tout à l'air OK!
Good Job :+1:
