### ISSUE TITLE
je ne peux pas mettre de fichier image dans la galerie de la fabrique

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#150]
![capture d ecran 2015-10-07 a 10 32 23](https://cloud.githubusercontent.com/assets/10072454/10332617/c9907648-6cde-11e5-8033-354b6f6bf327.png)

**Comment by zakxxi** [comment]
Quel est le poids de l'image envoyé ?

**Comment by Rouergue** [comment]
l'image n'était pas très lourde mais ça devait être un bug pcq ça a fonctionné après.
