### ISSUE TITLE
pb d'affichage dans la colonne de droite dans LA FABRIQUE

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#151]
- livre lié et nouveauté qui se rentrent dedans
- est-ce normal qu'il n'y ait pas de visuel au-dessus de "un nouveau roman à l'automne dans la coll. epik" ? Peut-être est-ce volontaire, je ne sais pas.

![capture d ecran 2015-10-07 a 10 40 08](https://cloud.githubusercontent.com/assets/10072454/10332769/d748eba2-6cdf-11e5-9003-2ee435e564cf.png)

**Comment by zakxxi** [comment]
Problème de CSS.

**Comment by Rouergue** [comment]
Peut-être que le plus simple est de supprimer complètement la mention "livre lié" (que le livre soit présent ou pas). De toute façon, quand il y a la couverture, on comprend bien que c'est le livre qui fait référence à l'article. 

De la même manière, on peut peut-être supprimer complètement la mention "média" pour les vidéos et mp3, qu'en pensez-vous ?

**Comment by zakxxi** [comment]
À faire en dev. sup si besoin.
