### ISSUE TITLE
Pourquoi le texte enrichi n'apparaît pas une fois la page publiée ?

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#152]
![capture d ecran 2015-10-07 a 10 53 44](https://cloud.githubusercontent.com/assets/10072454/10333077/c9aa9804-6ce1-11e5-9697-806ec9a48568.png)

![capture d ecran 2015-10-07 a 10 54 01](https://cloud.githubusercontent.com/assets/10072454/10333079/cd5d564e-6ce1-11e5-9027-7d68ff10eb5f.png)

**Comment by zakxxi** [comment]
Problème de CSS je regarde.

**Comment by zakxxi** [comment]
Tu peux désormais utiliser le format "Full HTML" qui réglera le problème.
![capture d ecran 2015-10-07 15 15 16](https://cloud.githubusercontent.com/assets/1446617/10338474/8d608154-6d06-11e5-9d31-c122882359cd.png)

**Comment by Rouergue** [comment]
Merci !
