### ISSUE TITLE
pourquoi la bibliographie de l'auteur est vide ?

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#154]
Il devrait y avoir le titre LA MALADROITE

![capture d ecran 2015-10-07 a 12 28 53](https://cloud.githubusercontent.com/assets/10072454/10335099/07c1e626-6cef-11e5-9656-ef7140927167.png)

**Comment by zakxxi** [comment]
J'étais en train de refaire une synchro, le problèmes des "trous" est réglé.
