### ISSUE TITLE
Comment faire pour ajouter un type d'événement ?

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#155]
dans la liste des événements sur le formulaire AGENDA ?

![capture d ecran 2015-10-07 a 14 07 42](https://cloud.githubusercontent.com/assets/10072454/10336975/eb7deb1e-6cfc-11e5-8b5a-95ebdb987185.png)

**Comment by zakxxi** [comment]
Petit problème de permissions résolu.

![image](https://cloud.githubusercontent.com/assets/1446617/10337509/697fe5fa-6d00-11e5-967d-b181d5d8b8ed.png)


http://prod.lerouergue.com/admin/structure/taxonomy/event_types

**Comment by Rouergue** [comment]
J'arrive bien sur la page avec la liste des différents types d'événement, mais je n'ai pas d'accès pour en créer un supplémentaire...

![capture d ecran 2015-10-07 a 14 49 35](https://cloud.githubusercontent.com/assets/10072454/10337856/cdc264aa-6d02-11e5-971b-7533e8cde1df.png)

**Comment by zakxxi** [comment]
Ça devrait fonctionner maintenant.
![capture d ecran 2015-10-07 15 32 36](https://cloud.githubusercontent.com/assets/1446617/10338877/b2b079c6-6d08-11e5-860d-a44bda341fee.png)

**Comment by Rouergue** [comment]
Ok, ça marche pour créer un événement.
Par contre, dans la liste de Taxonomy, je n'ai plus que la ligne faisant référence aux types d'événements et j'ai perdu l'accès aux fonctions, lectorat, thèmes, univers etc.

![capture d ecran 2015-10-07 a 15 48 46](https://cloud.githubusercontent.com/assets/10072454/10339355/3647c850-6d0b-11e5-8633-2ea5be6e222b.png)

**Comment by zakxxi** [comment]
Oui je les ai volontairement enlevés car ils sont importés de Mistral pour Fonctions, Lectorat, et Thèmes, et tout changement sera effacé à chaque synchro. Pour les Univers seul un administrateur peut en rajouter, car cela ne sert à rien tant que le mapping correspondant n'est pas codé.

**Comment by Rouergue** [comment]
ok
