### ISSUE TITLE
Texte disparu ? 

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#156]
Pourquoi n'y a-t-il pas de texte de présentation pour LES SOLITUDES SE RESSEMBLENT alors qu'il est bien présent sur mistral ?

![capture d ecran 2015-10-07 a 15 29 25](https://cloud.githubusercontent.com/assets/10072454/10338864/a21c1fd4-6d08-11e5-9dac-fec5f122f4f4.png)
![capture d ecran 2015-10-07 a 15 31 56](https://cloud.githubusercontent.com/assets/10072454/10338867/a594bf4a-6d08-11e5-88c6-b127f9355996.png)

**Comment by zakxxi** [comment]
C'est le champ 4e de couv qui est importé et pas petite phrase, donc normal dans ce cas de ne rien avoir côté Drupal.

**Comment by Rouergue** [comment]
Il me semble qu'on avait dit que la petite phrase était importée systématiquement par défaut et que celle-ci est remplacée par la 4e de couv' uniquement lorsque le champ 4e de couv dans mistral est rempli (ce qui n'est pas très courant pour l'instant)...

**Comment by Rouergue** [comment]
cf. mail du 15/10/2014

" 

• Récupération des 4e de couverture

Pour les textes de présentation des livres, celui-ci correspond à la "petite phrase" mistral, par défaut, lorsque le champ "4e de couv" de la fiche projet est vierge. Mais dès que ce champ est rempli, c'est ce contenu qui est à privilégier. Nous n'avons pas besoin de proposer la 4e de couv en téléchargement sous forme pdf ou jpeg.

 

Je vais récupérer la "petite phrase" dans le champ resume de la table book.

Dans la table book, on trouve 266 enregistrements pour lesquels ni le champ backcover ni le champ resume ne sont renseignés."

**Comment by zakxxi** [comment]
Oui en fait c'est la mécanique en place, on vient de vérifier dans le code.
Dans le cas des SOLITUDES… il y'a des saut de ligne dans 4e de couv… donc on importe ces sauts de lignes, il s'agit d'un ménage Mistral à effectuer, en jetant un œil rapide sur le DUMP on a d'autres bizarrerie dans ce champ, peut-être à regarder avec François pour faire un ménage "de masse".

![capture d ecran 2015-10-07 15 49 32](https://cloud.githubusercontent.com/assets/1446617/10339451/a4299c0e-6d0b-11e5-9ca8-76ca28d92c55.png)
