### ISSUE TITLE
Lien mal orienté

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#158]
Quand on clique sur "voir le livre" d'un bandeau actu, cela renvoie vers la page récap' de tout le catalogue au lieu de renvoyer sur la fiche livre.

![capture d ecran 2015-10-07 a 17 09 08](https://cloud.githubusercontent.com/assets/10072454/10341773/715cfd74-6d16-11e5-9347-f38602d799fd.png)

![capture d ecran 2015-10-07 a 17 09 00](https://cloud.githubusercontent.com/assets/10072454/10341749/5207006e-6d16-11e5-8ffd-dd4f2758d2ef.png)

**Comment by zakxxi** [comment]
Problème de lien :
http://prod.lerouergue.com/catalogue/les-autodafeurs-tome-3 et pas 
http://prod.lerouergue.com/catalogue/les-autodafeurs-tome-3-0
