### ISSUE TITLE
Pb affichage dans la fabrique

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#159]
les titres apparaissent en quinconce sur les visuels au lieu d'être tous justifiés en haut

![capture d ecran 2015-10-07 a 16 45 28](https://cloud.githubusercontent.com/assets/10072454/10341805/91eea3a8-6d16-11e5-922d-6a1717456f3e.png)

**Comment by zakxxi** [comment]
Attention, c'est qu'il y'a des sauts de lignes dans le champ "caption" sous les images…

A ce sujet nous n'utilisons peut-être pas la bonne méthode, le module "image_field_caption" est toujours associé à l'image, même dans les vues ou le résumé. Il faut peut-être créer un champ sur mesure pour les © et ne l'afficher que sur les nodes…

**Comment by Rouergue** [comment]
Je comprends d'où vient le décalage des titres du coup. En fait, j'ai volontairement mis  des sauts de lignes dans le champ "caption" pour séparer un peu les deux images, qu'elles ne soient pas collées dans la galerie. C'est un peu du bidouillage ; y a-t-il un autre moyen de le faire ?

![capture d ecran 2015-10-08 a 09 30 55](https://cloud.githubusercontent.com/assets/10072454/10360221/4cda0602-6d9f-11e5-8815-fd8a6ec1f58d.png)

**Comment by Rouergue** [comment]
Et ce serait pas mal, en effet, de créer un champ sur mesure pour les ©

**Comment by zakxxi** [comment]
Je vais créer un champ © pour les photos auteur, et supprimer le module image_field_caption, pour séparer les images dans Fabrique ce sera fait automatiquement par le CSS.
