### ISSUE TITLE
Optimisation du site pour la version 1.0

### ISSUE THREAD

**Issue by zakxxi** [abrege/lerouergue#163]
• Faire une branche Release 1.0 :+1: 
• Mettre à jour le profil d'installation :+1: 
• Passer en revue l'ensemble du site : champs, vues… :+1: 
• Supprimer les modules non utilisés : barcode… :+1: 
• Désactiver les interfaces graphiques des modules :+1: 
• Mettre en cache les vues :+1: 
• Formulaire de demande de catalogue:+1: 
• Basculer la prod sur la branche master:+1: 

Ouvrir une bouteille de champagne !!!

**Comment by Rouergue** [comment]
ah oui, il ne faut surtout pas oublier la bouteille de champagne !

**Comment by zakxxi** [comment]
![fireworks](https://cloud.githubusercontent.com/assets/1446617/10468384/0feeb6de-71ff-11e5-877f-3fb3a62bc8d0.jpg)
