### ISSUE TITLE
Ajouter un champ description pour les images de la galerie.

### ISSUE THREAD

**Issue by zakxxi** [abrege/lerouergue#164]

**Comment by zakxxi** [comment]
Alors je viens de revoir le principe des images dans la fabrique, ATTENTION tout le contenu image va être supprimé car j'ai du créer de nouveaux champs.

• Un nouveau champ "vignette" : pour mettre une image (obligatoire) qui apparait ensuite sur le bloc de la page d'accueil et les vues en liste
• Un groupe de champ "galerie" : avec un champ image + description

**Comment by Rouergue** [comment]
Ok merci. J'en ai profité pour remettre les images.
Par contre, il n'y a pas le petit espace entre les images

![capture d ecran 2015-10-08 a 14 43 35](https://cloud.githubusercontent.com/assets/10072454/10366474/027ca426-6dcb-11e5-87ec-bc39a90236ae.png)

Et j'ai l'impression que le premier champ "galerie" apparaît toujours (du coup, il est en double sur le formulaire).

![capture d ecran 2015-10-08 a 14 44 19](https://cloud.githubusercontent.com/assets/10072454/10366485/1b711890-6dcb-11e5-8615-6cf6ee4499b2.png)

Dernière chose, au-dessus de la couv' du livre lié, la mention "nouveauté" empiète sur l'intitulé.

![capture d ecran 2015-10-08 a 14 40 15](https://cloud.githubusercontent.com/assets/10072454/10366499/39dd96a0-6dcb-11e5-93c5-bec093a42ad4.png)

**Comment by zakxxi** [comment]
Patiente ;-) Pour tous les bugs graphiques ce sera la dernière étape, j'ai tout listé sur le ticket #161
