### ISSUE TITLE
Intégrer les description d'univers manquantes

### ISSUE THREAD

**Issue by zakxxi** [abrege/lerouergue#166]

**Comment by Rouergue** [comment]
ok, j'envoie ça par mail.
Merci !

**Comment by zakxxi** [comment]
Merci bien reçu, je les intègre prochainement.

**Comment by Rouergue** [comment]
Super, merci !
Par contre, aurai-je la main pour pouvoir faire des modifications sur les descriptifs ? A quel niveau ?

**Comment by zakxxi** [comment]
Ce sera possible via la taxonomie "Univers" et le champ description.

De notre côté il faut verrouiller la feature sur la prod.
