### ISSUE TITLE
Explorer le serveur à partir de la Fabrique ?

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#167]
Il n'y a pas de bouton permettant d'explorer le serveur à partir des formulaires de la Fabrique. Est-ce possible de le prévoir comme pour les autres formulaires (évenement, par exemple) ?

![capture d ecran 2015-10-08 a 16 37 11](https://cloud.githubusercontent.com/assets/10072454/10369521/006c0496-6ddb-11e5-88b3-1fb8fde12757.png)

**Comment by zakxxi** [comment]
Alors le bouton explorer le serveur est uniquement disponible dans le champ "body", afin d'enrichir le texte, il est aussi dispo sur la fabrique comme dans TOUS les champs "texte riche".

![capture d ecran 2015-10-08 18 10 24](https://cloud.githubusercontent.com/assets/1446617/10372672/4822a732-6de9-11e5-9c0f-f26824ee2ef6.png)
![capture d ecran 2015-10-08 18 10 28](https://cloud.githubusercontent.com/assets/1446617/10372673/4825b85a-6de9-11e5-82b5-615c38545205.png)
