### ISSUE TITLE
intégration d'un fichier mp3

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#168]
Est-il possible de faire lire le fichier mp3 directement dans le corps de la page (comme pour les vidéos) sans ouvrir une nouvelle fenêtre ? 

![capture d ecran 2015-10-08 a 16 49 48](https://cloud.githubusercontent.com/assets/10072454/10369868/c4854562-6ddc-11e5-818d-7d228185f79d.png)

![capture d ecran 2015-10-08 a 16 49 53](https://cloud.githubusercontent.com/assets/10072454/10369869/c69df542-6ddc-11e5-88e3-8ef8c2ac1dcd.png)

**Comment by zakxxi** [comment]
Ce comportement est prévu mais il faut passer par soundcloud pour héberger les fichiers MP3
https://soundcloud.com/

C'est exactement le même principe que pour les vidéos.

**Comment by Rouergue** [comment]
OK. J'ai donc essayé de créer un compte sur Soundcloud mais apparemment, mon adresse mail est déjà enregistrée. Est-ce vous qui avez créé un compte pour faire des essais ? Le nom du profil est 

![capture d ecran 2015-10-13 a 12 00 30](https://cloud.githubusercontent.com/assets/10072454/10451724/2c7725be-71a2-11e5-8d51-ce081d0f9f98.png)

**Comment by zakxxi** [comment]
Hum non peut-être Adèle ?
