### ISSUE TITLE
Import des livres (article) : notice d'erreur dans la console d'admin

### ISSUE THREAD

**Issue by jabberwooki** [abrege/lerouergue#170]
Après un import d'articles, la console d'admin Migrate (/admin/content/migrate/groups/mistral) indique 1008 messages d'erreur (1 message par article importé).
![mistral-migrations-admin-screen](https://cloud.githubusercontent.com/assets/1741337/10371749/1f0cf1b2-6de5-11e5-96cd-d0ee5f0f67a8.png)

Ces messages sont tous identiques : 
_Informational
Undefined index: timezone File /home/chris/dev/rouergue/profiles/rouergue/modules/contrib/date/date.field.inc, line 364(file: /home/chris/dev/rouergue/profiles/rouergue/modules/contrib/date/date.field.inc, line 364)_

C'est un problème connu du module Date, décrit dans un [ticket](https://www.drupal.org/node/2408093).
Le commentaire [#6](https://www.drupal.org/node/2408093#comment-9911033) indique que le problème est corrigé par le patch proposé, intégré à la version 2.9-rc1 du module Date. Le site tourne actuellement avec la version 2.8 de Date.
TODO : Après mise à jour du noyau et des modules contrib prévue avant mise en ligne (ticket #145), vérifier que ce message d'erreur a disparu.

NOTE : Contributor affiche lui-aussi des messages d'erreur (1190 messages, cf. copie d'écran), mais il s'agit d'un pb dans le module image_field_caption. Celui-ci devant être supprimé, il n'est pas nécessaire de traiter ce problème.

**Comment by zakxxi** [comment]
Réglé par là mise à jour
![image](https://cloud.githubusercontent.com/assets/1446617/10394883/447d0e18-6e9a-11e5-8804-ddda399ed4e4.png)
