### ISSUE TITLE
comment faire un lien d'une page vers la fabrique ?

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#171]
exemple, de la page livre "LES BILLES FONT LA COURSE" vers l'article de la fabrique sur "le monde en pyjamarama" ? 

![capture d ecran 2015-10-13 a 10 49 10](https://cloud.githubusercontent.com/assets/10072454/10450090/28e42aaa-7198-11e5-9beb-93a8503c3268.png)

**Comment by zakxxi** [comment]
il faut bien mettre un / avant l'url

/fabrique/le-monde-en-pyjamarama

![image](https://cloud.githubusercontent.com/assets/1446617/10460124/2457a3e6-71d3-11e5-9e90-fd504a01bcb2.png)
