### ISSUE TITLE
Page foreign rights > www.franceedition.org renvoie sur un autre site

### ISSUE THREAD

**Issue by zakxxi** [abrege/lerouergue#175]
![image](https://cloud.githubusercontent.com/assets/1446617/10466905/30e8a64a-71f7-11e5-961e-f2702595ebb8.png)

**Comment by zakxxi** [comment]
http://www.bief.org/ ???

**Comment by Rouergue** [comment]
Oui, c'est bizarre. Je ne comprends pas pourquoi franceedition.org renvoie sur ce site immobilier ?!!.
Les responsables du service des droits étant actuellement à la foire de Francfort, on a qu'à mettre le site de la BIEF effectivement. Et je verrai ça à leur retour.
