### ISSUE TITLE
vidéos dans la fabrique ?

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#180]
Est-ce normal que les vidéos aient disparues dans certains articles de la Fabrique ? C'est parce que vous avez fait des mises à jour ?

![capture d ecran 2015-10-14 a 09 29 35](https://cloud.githubusercontent.com/assets/10072454/10477406/2cc80dd0-7256-11e5-9e56-a24e99f567dc.png)

**Comment by zakxxi** [comment]
Peux-tu vider les caches de ton navigateur ? Je pense que le problème vient de là idem pour le #181

**Comment by Rouergue** [comment]
Ok, ça marche !
