### ISSUE TITLE
formulaire de demande de catalogue

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#182]
Il n'y a que la possibilité d'envoyer des catalogues en France et en Belgique via le formulaire ?

![capture d ecran 2015-10-14 a 09 57 09](https://cloud.githubusercontent.com/assets/10072454/10477916/3d187ce8-725a-11e5-9358-de5594896308.png)

**Comment by zakxxi** [comment]
Il me semble que c'est ce qui avait été prévu, sinon on met un champ "Pays" libre ?

**Comment by Rouergue** [comment]
Oui, c'est plus simple de mettre un champ "Pays" libre pour la demande de catalogue.
Merci !

**Comment by Rouergue** [comment]
Tu vas plus vite que ton ombre !
