### ISSUE TITLE
pages statiques

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#183]
Adrien, j'ai l'impression que tu n'es pas reparti du dernier fichier envoyé pour les pages statiques. La présentation de la maison, notamment n'est pas la bonne. Et, pour les pages presse, on avait rajouté les mails (avec lien vers boîtes mails). 

Pour la page "nous contacter", on avait demandé la création d’un lien avec renvoi directement sur la boîte mail de chacun (sauf pour Alzira).

Je te renvoie le fichier par mail.

![capture d ecran 2015-10-14 a 10 18 17](https://cloud.githubusercontent.com/assets/10072454/10478316/ed9c6668-725c-11e5-923f-bfb550371040.png)

**Comment by zakxxi** [comment]
Pour toutes les modifications relatives au contenu tu peux désormais le faire directement sur la prod, on fait un point la dessus tout à l'heure, idem pour les liens vers les adresses email.

**Comment by Rouergue** [comment]
Ok. Tu me diras où je peux les modifier !
