### ISSUE TITLE
infos sur texte enrichi ? 

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#188]
Ça veut dire quoi "créer un container DIV" ?

![capture d ecran 2015-10-14 a 16 23 28](https://cloud.githubusercontent.com/assets/10072454/10486625/213d3aaa-7290-11e5-811b-b87106f32c60.png)

Et "insert Teaser Break" ?

![capture d ecran 2015-10-14 a 16 23 38](https://cloud.githubusercontent.com/assets/10072454/10486642/2c6e5774-7290-11e5-9427-bde3c7aca9d7.png)

Et puis-je agir sur l'interlignage dans le texte ? 
Je n'arrive pas à rapprocher la ligne tél. du nom des contacts, par exemple :

![capture d ecran 2015-10-14 a 16 26 04](https://cloud.githubusercontent.com/assets/10072454/10486667/4cab7b70-7290-11e5-9692-cfa91bc80f82.png)

**Comment by zakxxi** [comment]
Je t'appelle ce sera plus simple à expliquer ;-)
