### ISSUE TITLE
1 titre manquant

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#189]
L'éditeur des romans jeunesse me fait très justement remarquer qu'il manque un titre : CORNICHON JIM (sorti en mars 2015). Tout à l'air pourtant correct sur Mistral... Quid ?

![capture d ecran 2015-10-14 a 16 34 56](https://cloud.githubusercontent.com/assets/10072454/10486917/a4beb240-7291-11e5-9bc9-698874c3abe6.png)

**Comment by zakxxi** [comment]
Je pense que c'est car il n'a pas de statut.

**Comment by Rouergue** [comment]
c'est bizarre, il y a plusieurs champs "status" dans mistral et je ne sais pas trop pourquoi le champ statut "simple" n'est pas renseigné (en "disponible"). Peux-tu nous dire d'où ça vient, François ?

![capture d ecran 2015-10-14 a 17 01 37](https://cloud.githubusercontent.com/assets/10072454/10487722/ad44d062-7295-11e5-8e9c-0907e39bcf72.png)

Est-ce que, quand ce statut est vide, cela veut dire que c'est dispo par défaut ?

**Comment by zakxxi** [comment]
Après nouveau dump c'est bon !
http://prod.lerouergue.com/catalogue/cornichon-jim
