### ISSUE TITLE
vignettes dans colonne de droite dans LA FABRIQUE

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#190]
Est-il possible de mettre les vignettes en plus petit ?
Car on a l'impression que la colonne de gauche fait partie de l'article principal...

![capture d ecran 2015-10-15 a 12 03 00](https://cloud.githubusercontent.com/assets/10072454/10513410/bb55878e-7347-11e5-967e-b0fcabf17aca.png)

**Comment by zakxxi** [comment]
On peut partir sur ça :
![image](https://cloud.githubusercontent.com/assets/1446617/10514899/fc091cf6-7350-11e5-9c0a-a3223640eac4.png)

Le titre est changeable.

**Comment by Rouergue** [comment]
Et peux-tu laisser les vignettes à ce petit format (ou un chouilla plus grand) mais mettre le titre en dessous et non pas à droite de la vignette ?

Pour le nom "fabrique", le remplacer finalement par "à voir aussi dans la fabrique", stp.

Merci !
