### ISSUE TITLE
bandeau AGENDA sur la page d'accueil

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#191]
Pourquoi n'a-t-on pas les petits ronds rouge qui permettent de voir les autres annonces du mois, comme pour les nouveautés ? 

![capture d ecran 2015-10-15 a 12 10 41](https://cloud.githubusercontent.com/assets/10072454/10513454/f1e7c334-7347-11e5-9a44-4186384cf48b.png)

**Comment by zakxxi** [comment]
Non prévu dans le cahier des charges.

**Comment by Rouergue** [comment]
OK. L'idée serait juste de faire une ligne sur toute la largeur de la page, avec la mention "voir tout l'agenda" à gauche (avec lien vers la page récap' de l'agenda) et sur la même ligne mais à droite les liens facebook.

**Comment by zakxxi** [comment]
![image](https://cloud.githubusercontent.com/assets/1446617/10521002/9ae533ac-736d-11e5-85a0-b912c1ce9dcd.png)
