### ISSUE TITLE
Scroll bar manquantes

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#192]
Au niveau des colonnes de droite, dans la Fabrique et dans l'Agenda. Ce qui empêche de voir l'ensemble des articles publiés dans la Fabrique, par exemple (il manque notamment l'article sur Méli-mélodie).

![capture d ecran 2015-10-15 a 12 12 30](https://cloud.githubusercontent.com/assets/10072454/10513469/0aba75b4-7348-11e5-89fa-fd7d82da8e58.png)

![capture d ecran 2015-10-15 a 12 14 18](https://cloud.githubusercontent.com/assets/10072454/10513472/0e488748-7348-11e5-9101-ff6a596f7044.png)

**Comment by zakxxi** [comment]
Pour l'instant c'est paramétré sur les 4 items les plus récents, ça peut se changer en 5 ou 6, plus me paraît trop. Par contre on ne peut pas faire de scrollbar.

**Comment by Rouergue** [comment]
Ok pour 6 items les plus récents (dans la fabrique et dans l'agenda) pour la colonne de droite.
