### ISSUE TITLE
Pb d'affichage d'une image de 550 pixels de large qui rentre dans les colonnes de droite...

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#195]
... quand on réduit la taille de l'écran.

![capture d ecran 2015-10-19 a 14 28 56](https://cloud.githubusercontent.com/assets/10072454/10577762/ed893894-766d-11e5-8aea-254555eac793.png)

**Comment by zakxxi** [comment]
Effectivement c'est parce que les images sont dans le "corps" du texte enrichi, je vais corriger ça.

**Comment by Rouergue** [comment]
Adrien,

J'ai à nouveau le même problème quand je veux ajouter une image dans le corps du texte d'une page de livre.
Pourtant, je respecte bien les 550 pixels de large pour le tableau. Sais-tu d'où ça peut venir ?
Merci pour ton aide (bientôt je ne t'embêterai plus !...).

Mathilde

[cid:02BFEF69-D77B-4423-A583-46082FB9731A]

De : Adrien Revel <notifications@github.com<mailto:notifications@github.com>>
Répondre à : abrege/lerouergue <reply@reply.github.com<mailto:reply@reply.github.com>>
Date : lundi 19 octobre 2015 15:22
À : abrege/lerouergue <lerouergue@noreply.github.com<mailto:lerouergue@noreply.github.com>>
Cc : Mathilde Gautron-Davienne <mathilde.davienne@lerouergue.com<mailto:mathilde.davienne@lerouergue.com>>
Objet : Re: [lerouergue] Pb d'affichage d'une image de 550 pixels de large qui rentre dans les colonnes de droite... (#195)


Effectivement c'est parce que les images sont dans le "corps" du texte enrichi, je vais corriger ça.

-

**Comment by Rouergue** [comment]
Peux tu m'envoyer l'URL de la page concernée stp.
