### ISSUE TITLE
Epub page catalogue

### ISSUE THREAD

**Issue by Fchallier** [abrege/lerouergue#196]
Est-ce normal ? 

![rouergue-epub](https://cloud.githubusercontent.com/assets/9974750/10601128/b81cb0b2-770f-11e5-81c3-0b6aba2a3cb2.png)

**Comment by Rouergue** [comment]
Effectivement, il me semble que les epub (pour lesquels nous n'avons pas de visuel en général) n'apparaissaient pas sur les pages récap' du catalogue et des univers. Quid ?

**Comment by zakxxi** [comment]
Effectivement on en avait parlé, je rajoute un filtre sur cette vue afin d'exclure les titres contenant (EPUB).

![capture d ecran 2015-10-20 11 21 33](https://cloud.githubusercontent.com/assets/1446617/10603163/bd79bdc2-771c-11e5-92bf-f7d9a0f9b05b.png)

**Comment by Rouergue** [comment]
Ce filtre peut-il fonctionner aussi pour les pages récap' des biblios auteurs ?

**Comment by zakxxi** [comment]
Oui, par contre pour la vue "livres du même auteur" c'est plus compliqué. Je le mets en place sur la vue biblio ?

**Comment by Rouergue** [comment]
Oui, au moins sur la vue biblio, stp !
Merci !

**Comment by zakxxi** [comment]
C'est bon pour les 2 vues en fait ça a l'air de fonctionner !

**Comment by Rouergue** [comment]
Génial !!!
