### ISSUE TITLE
Message d'erreur lors de "drush mi ArticleContributors"

### ISSUE THREAD

**Issue by zakxxi** [abrege/lerouergue#21]
``` Could not find host entity of the field collection to import.             [error] ```

**Comment by jabberwooki** [comment]
Ce n'est pas un bug. C'est une situation normale.
Cela se produit lorsque Drupal essaie d'importer un contributeur, mais que le ou les livres auxquels il doit être lié n'on pas été importés, eux. C'est le cas par exemple si le livre est interdit à la vente ou s'il n'est pas encore dans un plan commercial (je sais pas si c'est exactement comme ça qu'il faut dire).
L'idéal aurait été que le dump Mistral ne contienne que des données à importer, c'est-à-dire que le tri entre ce qui est à afficher sur le site et ce qu'il faut écarter soit fait au moment de l'extraction de la base Mistral, et non au moment de l'import dans Drupal.
