### ISSUE TITLE
titre noté en interdit à la vente sur mistral et qui ne devrait pas apparaître sur le site

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#43]
![capture d ecran 2014-12-04 a 11 38 30](https://cloud.githubusercontent.com/assets/10072454/5296949/18f8685c-7baa-11e4-8c25-8f3ec9ecd2f9.png)

**Comment by jabberwooki** [comment]
Effectivement, il n'y a pour l'instant aucun filtre sur le statut d'un article (0=publiable, 1=interdit à la vente, 2=titre manquant, 3=titre épuisé).
J'ai modifié le code d'import migrate pour écarter les statusid=0.
Il faut faire un roll-back puis ré-importer pour voir disparaitre les livres interdits à la vente.

Attention ! Même si la date du livre "Les objets du désir" est bien à 9999, son statut par contre est égal à 0, donc ce livre apparaitra quand-même.

Suggestion : pourquoi exporter dans le dump mysql des livres qui ne doivent pas apparaitre sur le site ? Autant filtrer ces livres à l'export.
