### ISSUE TITLE
ISBN qui n'apparaît pas

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#45]
Pourquoi l'ISBN n'apparaît pas au-dessus du gencod ? 

![capture d ecran 2014-12-08 a 14 49 07](https://cloud.githubusercontent.com/assets/10072454/5340151/7cca2f36-7ee9-11e4-9760-f92ceefb2976.png)

**Comment by jabberwooki** [comment]
Lors de l'importation, c'est le bon champ, isbn13, qui est sélectionné. Mais lors du field mapping, c'était le champ isbn et non isbn13 qui était utilisé. D'où l'absence de valeur à l'affichage.
C'est corrigé. Il faut un ré-import des données mistral.
