### ISSUE TITLE
Nom auteur manquant

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#53]
Dans la bande Nouvautés sur l'album LA NUIT QUAND JE DORS (alors que le nom de l'auteur-illustateur apparaît bien sur la fiche livre).

![capture d ecran 2014-12-08 a 15 53 01](https://cloud.githubusercontent.com/assets/10072454/5340972/6561a7b2-7ef2-11e4-9ecf-aba3920e7725.png)

**Comment by jabberwooki** [comment]
Pour ce livre, "La nuit quand je dors", l'auteur n'apparait pas parce qu'il n'y a aucun auteur enregistré. Un seul contributeur, Ronald CURCHOD, est lié à ce livre. Il est indiqué comme auteur principal, mais enregistré avec la fonction "illustrateur".

La requête à utiliser pour lister les contributeurs rattachés à un livre est la suivante.

SELECT b.bookid, b.title, c.name, c.firstname, c.pseudoname, c.pseudofirstname, f.name, bc.ismain, bc.iscommunicable
from book b
join bookcontributor bc on bc.bookid=b.bookid
join contributor c on c.contributorid=bc.contributorid
join function f on f.functionid=bc.functionid
where b.bookid = xxxx
(pour le présent livre, bookid=29238).
