### ISSUE TITLE
Format qui n'apparaît pas

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#57]
![capture d ecran 2014-12-09 a 16 52 42](https://cloud.githubusercontent.com/assets/10072454/5360316/d3d24ee6-7fc3-11e4-8995-e086eefb632e.png)

**Comment by jabberwooki** [comment]
Après vérification dans la base mistral exportée, le format du livre ci-dessus n'apparait pas parce que les données mistral sont incohérentes. Le finalformatid de ce bouquin (articleid=18920, bookid=15575), stocké dans la table fabricationplan, est égal à 1331 et dans la table format il n'existe au formatid égal à 1331.

A NOTER !
D'après le commentaire posté par Adrien juste avant, il semble que le format ne soit plus géré dans un seul champ mais dans 2 champs distincts.
Cela va demander une modification évolutive du code de synchronisation et de la structure du type de contenu article dans Drupal.
A discuter.
