### ISSUE TITLE
Pourquoi le nombre de page n'apparaît pas

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#58]
Alors qu'il est bien dans mistral

![capture d ecran 2014-12-09 a 16 53 45](https://cloud.githubusercontent.com/assets/10072454/5360345/feea6f32-7fc3-11e4-888c-1a80991cf5bf.png)

**Comment by jabberwooki** [comment]
Pour ce livre, la colonne nbpage de la table book contient la valeur 176.
Mais la colonne finalnbpages de la table fabricationplan contient NULL.
C'est cette seconde valeur qui est importée.

A NOTER !
Pour corriger ce défaut, il faut soit renseigner correctement le nombre final de pages dans Mistral avant export, soit modifier le code d'importation dans Drupal en ajoutant une conditionnelle.
Nécessite un travail de maintenance évolutive.
A discuter.
