### ISSUE TITLE
Ne pas faire apparaître le même titre dans la rubrique "du même auteur"

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#66]
![capture d ecran 2014-12-15 a 14 21 04](https://cloud.githubusercontent.com/assets/10072454/5436371/a57ec1e0-8465-11e4-8919-2e67ef668e08.png)

**Comment by jabberwooki** [comment]
Cela fonctionne déjà ainsi.
Dans le cas présent, il s'agit de deux livres différents, une première édition + nouvelle édition revisitée.
