### ISSUE TITLE
Ne pas faire apparaître les intitulés de rubrique ("du même auteur", "biblio", "agenda", etc.) lorsque la rubrique est vide

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#67]
![capture d ecran 2014-12-15 a 14 22 13](https://cloud.githubusercontent.com/assets/10072454/5436382/dcccc656-8465-11e4-9ec3-8ebd72deedef.png)

**Comment by jabberwooki** [comment]
Comportement mis en place pour les blocs "Du même auteur" et "Dans la même série" de la fiche livre.
Sur la fiche auteur, le bloc "Bibliographie" contient toujours au moins un livre donc pas besoin de le faire disparaitre. Et lorsque "Agenda de l'auteur" est vide, le titre n'apparait pas car c'est un champ et non un bloc, et Drupal cache automatiquement les labels des champs non renseignés.
