### ISSUE TITLE
Garder les ital et bold des textes tels qu'ils sont extraits de mistral

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#71]

**Comment by zakxxi** [comment]
Je ne me souviens plus si cela a été géré ou pas.

**Comment by jabberwooki** [comment]
Corrigé.
Le problème était le suivant : le champ field_body (Petite phrase) était bien paramétré au format Full HTML, mais l'import des données depuis Mistral, sans info particulière, faisait que Drupal sauvegardait ce champ au format Plain Text. Le code d'import était : 
__$this->addFieldMapping('body', 'backcover');__

La modification de ce code en : 
__$this->addFieldMapping('body', 'backcover')->arguments(array('format' => 'full_html'));__
telle qu'indiquée dans le [ticket suivant](https://www.drupal.org/node/1108694) permet d'importer au format Full HTML, mais avec ce message d'erreur : 
_"The field mapping arguments() method is now deprecated - please use subfield notation instead"_

Méthode dépréciée, donc à éviter. La bonne écriture, trouvé dans cet [autre ticket](https://www.drupal.org/node/2171297), est la suivante : 
__$this->addFieldMapping('body', 'backcover');
$this->addFieldMapping('body:format', NULL, FALSE)->defaultValue('full_html');__
