### ISSUE TITLE
il manque le champ "mail" dans la partie administrative pour la création d'événement (dans l'agenda)

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#72]
Mail indiqué ici à la place du "titre site"

![capture d ecran 2015-01-06 a 14 12 18](https://cloud.githubusercontent.com/assets/10072454/5629026/00561afa-95af-11e4-9cf0-d95a33571c1f.png)

**Comment by zakxxi** [comment]
Pour faire un lien vers une boite e.mail il suffit de rentrer :
```
mailto:toto@toto.com
```
dans le champ URL
