### ISSUE TITLE
problème de déroulement des menus au niveau de l'administration

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#73]
Difficultés à atteindre le 3e niveau (les menus s'effacent avant que j'ai pu l'atteindre ou dès que la souris est un peu trop à droite) + menus du site (accueil / catalogues, etc.) qui cachent l'affichage complet des menus adminstrateur.

![capture d ecran 2015-01-06 a 14 22 14](https://cloud.githubusercontent.com/assets/10072454/5629052/79981148-95af-11e4-80fd-0b7307c6457a.png)

**Comment by zakxxi** [comment]
Problème de Z-index à régler
