### ISSUE TITLE
comment supprimer du contenu ? 

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#74]
Je n'arrive à retrouver le lien pour le faire (que ce soit du contenu dans l'agenda, les workshops ou actualité). Je ne vois que les menus pour ajouter du contenu. 

![capture d ecran 2015-01-06 a 14 39 08](https://cloud.githubusercontent.com/assets/10072454/5629264/d251f676-95b1-11e4-8fbc-b1f4b9278be0.png)

**Comment by Rouergue** [comment]
ah ça y est, je crois que j'ai trouvé ! Il suffit d'aller sur l'événement et de le supprimer à partir de la page ouverte... Il n'y a pas de raccourci au niveau du menu, c'est bien ça ?

**Comment by jabberwooki** [comment]
On peut supprimer un contenu de 2 manières :
- depuis le formulaire de modification du contenu en question, comme tu l'as découvert toi-même.
- depuis la page qui liste tous les contenus, en cliquant sur le lien "Contenu" au premier niveau du menu d'administration. Dans cette page, il est possible de filtrer les contenus par type ou de les trier, par titre ou par date de mise à jour par exemple.
