### ISSUE TITLE
Où puis-je indiquer l'url de la page vers laquelle je veux renvoyer (page titre, auteur ou agenda), à partir des encadrés actualité ?

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#75]
![capture d ecran 2015-01-06 a 15 35 36](https://cloud.githubusercontent.com/assets/10072454/5629974/bf5cee60-95b9-11e4-9b4b-d1bf7da58b8c.png)

**Comment by zakxxi** [comment]
Dans le champ URL, mais pour l'instant ce champ est masqué de l'affichage, il faut voir si on peut faire le lien l'image ou si on créé un bouton à cet effet.
