### ISSUE TITLE
Workshop : Est-il possible de mentionner un titre (à paraître), même s'il n'est pas encore dans mistral ?

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#76]
Auquel cas, il ne pourra pas y avoir encore de lien, mais le titre sera quand même mentionné. 

![capture d ecran 2015-01-06 a 16 01 09](https://cloud.githubusercontent.com/assets/10072454/5630696/659a9722-95c0-11e4-90d9-7b2e4d6cd73f.png)

**Comment by jabberwooki** [comment]
Non, il n'est possible de lier un workshop qu'à un (ou plusieurs) titres déjà importés dans Drupal.
Pour pouvoir mentionner un titre à paraître, il faudrait rajouter un champ texte libre donc modifier le type de contenu Article dans Drupal.
