### ISSUE TITLE
Workshop : À quoi correspond la notion de "poids" situé à droite de chaque image téléchargée ?

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#77]
![capture d ecran 2015-01-06 a 16 03 29](https://cloud.githubusercontent.com/assets/10072454/5630731/9f7f0810-95c0-11e4-8894-1891140fc6b5.png)

**Comment by jabberwooki** [comment]
Le poids permet d'ordonner les images. Drupal affichera les images dans l'ordre de poids ascendant, l'image de poids 0 en premier jusqu'à l'image de poids le plus grand. Il faut donc changer le poids d'une image si l'on veut modifier sa position à l'affichage.

Mais on peut faire ça plus simplement. Il faut cliquer sur le symbole situé en haut à droite (entouré en rouge ci-dessous) pour voir disparaitre la colonne poids et apparaître complètement à gauche une poignée au niveau de chaque image. Il suffit de glisser-déposer une image pour modifier sa position.
En cliquant à nouveau sur le symbole de droite, les poignées disparaissent et on ré-obtient la colonne des poids.

__*Copie d'écran avec les poids*__
![workshop-image-poids](https://cloud.githubusercontent.com/assets/1741337/5631957/160a8018-95cb-11e4-96cf-fa26c7bc1c8f.png)

__*Copie d'écran avec les poignées*__
![workshop-image-poignee](https://cloud.githubusercontent.com/assets/1741337/5631969/26203100-95cb-11e4-8e0f-c2adc5d13e8b.png)
