### ISSUE TITLE
Comment puis-je changer l'ordre des images dans la galerie de workshops ?

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#78]
J'ai essayé en changeant l'ordre au niveau des onglets "poids", mais cela ne fonctionne pas.

![capture d ecran 2015-01-06 a 16 04 53](https://cloud.githubusercontent.com/assets/10072454/5630748/c489ac0a-95c0-11e4-8b16-7da704bdcc9d.png)

**Comment by jabberwooki** [comment]
Normalement, ça fonctionne. Il ne faut pas oublier d'enregistrer le workshop après avoir changé la valeur des poids. Profites-en pour essayer d'ordonner les images à l'aide des poignées (voir explication dans le ticket précédent n°77).
