### ISSUE TITLE
Workshop : Puis-je décider de la taille des images de la galerie ?

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#79]
Certaines images sont beaucoup trop grosses et n'apparaissent pas en entier.

![capture d ecran 2015-01-06 a 16 28 32](https://cloud.githubusercontent.com/assets/10072454/5630782/2389747e-95c1-11e4-90a6-8c8f1e55979a.png)

**Comment by zakxxi** [comment]
Il faut que l'on décide comment afficher ces images, le style "tumblr" me semble être une bonne piste.
