### ISSUE TITLE
Workshop : Est-il possible de faire apparaître la galerie d'images sous forme de tumblr et non pas chaque image l'une en-dessous de l'autre, en colonne

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#80]
![capture d ecran 2015-01-06 a 16 30 46](https://cloud.githubusercontent.com/assets/10072454/5630813/62b6d6dc-95c1-11e4-9257-00b5d1b6a1b7.png)

**Comment by zakxxi** [comment]
Duplicate #79
