### ISSUE TITLE
Agenda : peut-on mentionner des noms d'intervenant n'étant pas indiqués comme contributeurs dans mistral ?

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#82]
Exple : présence de la directrice de coll. Sylvie Gracia à une rencontre.
Il faudrait que son nom apparaisse, même s'il n'y a pas de lien vers sa bio/biblio.

![capture d ecran 2015-01-06 a 14 58 20](https://cloud.githubusercontent.com/assets/10072454/5630849/c280f674-95c1-11e4-8330-8822dc1b5124.png)

**Comment by zakxxi** [comment]
Compliqué à faire avec le système actuel, le champ "Auteurs" est lié à la base de donnée, dans ces cas particuliers il faut peut être ajouter ces noms dans le champ "body"
