### ISSUE TITLE
Agenda : un seul visuel possible ?

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#83]
Est-il possible de faire apparaître plusieurs visuels au niveau des descriptifs des évenements (exple : photo auteur + couv livre + photo du lieu de la rencontre + logo du salon) ?

![capture d ecran 2015-01-06 a 14 50 52](https://cloud.githubusercontent.com/assets/10072454/5630874/14eec13e-95c2-11e4-8f71-8d4f8f3472d8.png)

**Comment by zakxxi** [comment]
On peut activer un "texte riche" sur le champ description avec un ajout possible d'image.
