### ISSUE TITLE
Actualité : problème de format

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#86]
Lorsque je fais une copie d'écran, j'arrive à un format 1142 x 433 px, ce qui est différent du format demandé = 850 x 425 px. Du coup, les visuels sont coupés.

![capture d ecran 2015-01-06 a 16 59 10](https://cloud.githubusercontent.com/assets/10072454/5631272/9292a288-95c5-11e4-9c1f-6becd448db16.png)

![capture d ecran 2015-01-06 a 17 01 03](https://cloud.githubusercontent.com/assets/10072454/5631277/9d793cf2-95c5-11e4-9609-2282fb7bd1ef.png)

**Comment by zakxxi** [comment]
Le format du bandeau est 1140 × 430
