### ISSUE TITLE
Téléchargement d'images

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#87]
Est-ce possible d'ajouter le format pdf pour le téléchargement d'images ?

![capture d ecran 2015-01-06 a 17 03 09](https://cloud.githubusercontent.com/assets/10072454/5631325/f7ffe27a-95c5-11e4-8c4f-012f0e6ed69e.png)

**Comment by zakxxi** [comment]
Non les images doivent être en JPG, PNG ou GIF les PDF ne peuvent être utilisés que sur les champs "pages intérieures".
