### ISSUE TITLE
Pourquoi n'ai-je plus accès à la partie administration ?

### ISSUE THREAD

**Issue by Rouergue** [abrege/lerouergue#90]
![capture d ecran 2015-01-09 a 16 30 45](https://cloud.githubusercontent.com/assets/10072454/5681943/edc85716-981c-11e4-8b6b-2ad8098c7f3b.png)

**Comment by jabberwooki** [comment]
Par défault, Drupal conserve l'authentification d'un utilisateur, quel qu'il soit, pendant 2000000 secondes, ce qui fait un peu plus de 23 jours. Je viens de vérifier que, pour le compte webmaster, la dernière connexion remonte à 24 jours.

Il suffit donc que tu te reconnectes avec les identifiants webmaster via l'url suivante :
http://rouergue.abrege.net/user
